config/routes.rb
Rails.application.routes.draw do
  resources :citations
  root to: 'citations#index'
end

app/models/citation.rb
class Citation < ActiveRecord::Base
  has_one :Geometry

  def self.build_heat_map_json(citations_list)
    heat_map_arr = []
    day_count = {1 => {}, 2 => {}, 3 => {}, 4 => {}, 5 => {}, 6 => {}, 7 => {}}
    citations_list.each do |c|
      unless c.issue_date.blank?
        current_issue_date = c.issue_date
        current_wday = current_issue_date.wday + 1
        current_hour = current_issue_date.hour + 1
        unless day_count[current_wday][current_hour].nil?
          day_count[current_wday][current_hour] += 1
        else
          day_count[current_wday][current_hour] = 1
        end
      end
    end
    day_count.each do |k,v|
      v.each do |i,j|
        heat_map_arr << {"day" => k, "hour" => i, "value" => j}
      end
    end
    heat_map_arr
  end

  def self.issued_between(time1, time2)
    where("issue_date >= ? and issue_date <= ?", time1, time2)
  end

  def self.issued_since(time)
    where("issue_date >= ? and issue_date <= ?", time, Time.now)
  end

  def self.issued_within_last_week
    where("issue_date >= ?", 1.week.ago)
  end

  def self.issued_within_last_month
    where("issue_date >= ?", 1.month.ago)
  end

  def self.issued_within_last_three_months
    where("issue_date >= ?", 3.months.ago)
  end

  def self.issued_within_last_six_months
    where("issue_date >= ?", 6.months.ago)
  end

  def self.issued_within_last_nine_months
    where("issue_date >= ?", 9.months.ago)
  end

  def self.issued_within_last_year
    where("issue_date >= ?", 1.year.ago)
  end

end

app/models/geometry.rb
class Geometry < ActiveRecord::Base
    belongs_to :Citation
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  before_action :set_citation, only: [:show, :edit, :update, :destroy]

  # GET /citations
  # GET /citations.json
  def index
    #@citations = Citation.all
    citations = Citation.issued_within_last_week
    unless params.nil?
      if params.has_key?(:time_scope)
        if params[:time_scope] == "Last Week"
          #Rails.logger.info "time scope => Last Week"
          citations = Citation.issued_within_last_week
        end
        if params[:time_scope] == "Last Month"
          #Rails.logger.info "time scope => Last Month"
          citations = Citation.issued_within_last_month
        end
        if params[:time_scope] == "Last 3 Months"
          #Rails.logger.info "time scope => Last 3 months"
          citations = Citation.issued_within_last_three_months
        end
        if params[:time_scope] == "Last 6 Months"
          #Rails.logger.info "time scope => Last 6 months"
          citations = Citation.issued_within_last_six_months
        end
        if params[:time_scope] == "Last 9 Months"
          #Rails.logger.info "time scope => Last 9 months"
          citations = Citation.issued_within_last_nine_months
        end
        if params[:time_scope] == "Last Year"
          #Rails.logger.info "time scope => Last Year"
          citations = Citation.issued_within_last_year
        end
      end
    end
    @citations = Citation.build_heat_map_json(citations)
    #Rails.logger.info("*****************")
    #Rails.logger.info "Total Citations: #{citations.count}"
    @citations
  end

  # GET /citations/1
  # GET /citations/1.json
  def show
  end

  # GET /citations/new
  def new
    @citation = Citation.new
  end

  # GET /citations/1/edit
  def edit
  end

  # POST /citations
  # POST /citations.json
  def create
    @citation = Citation.new(citation_params)

    respond_to do |format|
      if @citation.save
        format.html { redirect_to @citation, notice: 'Citation was successfully created.' }
        format.json { render :show, status: :created, location: @citation }
      else
        format.html { render :new }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citations/1
  # PATCH/PUT /citations/1.json
  def update
    respond_to do |format|
      if @citation.update(citation_params)
        format.html { redirect_to @citation, notice: 'Citation was successfully updated.' }
        format.json { render :show, status: :ok, location: @citation }
      else
        format.html { render :edit }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citations/1
  # DELETE /citations/1.json
  def destroy
    @citation.destroy
    respond_to do |format|
      format.html { redirect_to citations_url, notice: 'Citation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citation
      @citation = Citation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def citation_params
      params.require(:citation).permit(:citation_num, :issue_date, :street_location, :violation, :geometry_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/views/citations/_form.html.haml
= simple_form_for(@citation) do |f|
  = f.error_notification

  .form-inputs
    = f.input :citation_num
    = f.input :issue_date
    = f.input :street_location
    = f.input :violation
    = f.input :geometry_id

  .form-actions
    = f.button :submit

app/views/citations/edit.html.haml
%h1 Editing citation

= render 'form'

= link_to 'Show', @citation
\|
= link_to 'Back', citations_path

app/views/citations/index.html.haml
%h1 City of Albuquerque Parking Citations 
%h2#time_period Time Period:
%h2#total_citations Total Citations:

#chart
#dataset-picker

:javascript
  $(document).ready(function() {
  var margin = { top: 50, right: 0, bottom: 100, left: 30 },
          width = 960 - margin.left - margin.right,
          height = 430 - margin.top - margin.bottom,
          gridSize = Math.floor(width / 24),
          legendElementWidth = gridSize*2,
          buckets = 9,
          colors = ["#ffffd9","#edf8b1","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#253494","#081d58"], // alternatively colorbrewer.YlGnBu[9]
          days = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
          times = ["12a", "1a", "2a", "3a", "4a", "5a", "6a", "7a", "8a", "9a", "10a", "11a", "12p", "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p", "10p", "11p"];
          datasets = ["Last Week", "Last Month", "Last 3 Months", "Last 6 Months", "Last 9 Months", "Last Year"];

      var svg = d3.select("#chart").append("svg")
          .attr("width", width + margin.left + margin.right)
          .attr("height", height + margin.top + margin.bottom)
          .append("g")
          .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

      var dayLabels = svg.selectAll(".dayLabel")
          .data(days)
          .enter().append("text")
            .text(function (d) { return d; })
            .attr("x", 0)
            .attr("y", function (d, i) { return i * gridSize; })
            .style("text-anchor", "end")
            .attr("transform", "translate(-6," + gridSize / 1.5 + ")")
            .attr("class", function (d, i) { return ((i >= 0 && i <= 4) ? "dayLabel mono axis axis-workweek" : "dayLabel mono axis"); });

      var timeLabels = svg.selectAll(".timeLabel")
          .data(times)
          .enter().append("text")
            .text(function(d) { return d; })
            .attr("x", function(d, i) { return i * gridSize; })
            .attr("y", 0)
            .style("text-anchor", "middle")
            .attr("transform", "translate(" + gridSize / 2 + ", -6)")
            .attr("class", function(d, i) { return ((i >= 8 && i <= 17) ? "timeLabel mono axis axis-worktime" : "timeLabel mono axis"); });

      //var heatmapChart = d3.json(my_data, function(error, data) {
      var heatmapChart = function(data) {
        data.forEach(function(d) {
          //console.log("day" + parseInt(d.day));
          //console.log("hour" + d.hour);
          //console.log("value" + d.value);
          return {
            day: +d.day,
            hour: +d.hour,
            value: +d.value
          }
        });

          //var totalSum = d3.sum(data, function(d) { return d.value; });

          var colorScale = d3.scale.quantile()
              .domain([0, buckets - 1, d3.max(data, function (d) { return d.value; })])
              .range(colors);

          var cards = svg.selectAll(".hour")
              .data(data, function(d) {return d.day+':'+d.hour;});

          cards.append("title");

          cards.enter().append("rect")
              .attr("x", function(d) { return (d.hour - 1) * gridSize; })
              .attr("y", function(d) { return (d.day - 1) * gridSize; })
              .attr("rx", 4)
              .attr("ry", 4)
              .attr("class", "hour bordered")
              .attr("width", gridSize)
              .attr("height", gridSize)
              .style("fill", colors[0]);

          cards.transition().duration(1000)
              .style("fill", function(d) { return colorScale(d.value); });

          cards.select("title").text(function(d) { return d.value; });
          
          cards.exit().remove();

          var legend = svg.selectAll(".legend")
              .data([0].concat(colorScale.quantiles()), function(d) { return d; });

          legend.enter().append("g")
              .attr("class", "legend");

          legend.append("rect")
            .attr("x", function(d, i) { return legendElementWidth * i; })
            .attr("y", height)
            .attr("width", legendElementWidth)
            .attr("height", gridSize / 2)
            .style("fill", function(d, i) { return colors[i]; });

          legend.append("text")
            .attr("class", "timeLabel mono axis axis-worktime")
            .text(function(d) { return "≥ " + Math.round(d); })
            .attr("x", function(d, i) { return legendElementWidth * i; })
            .attr("y", height + gridSize);

          legend.exit().remove();

        //});  
        };  

      
      var datasetpicker = d3.select("#dataset-picker").selectAll(".dataset-button")
        .data(datasets);

      (function() {
        //console.log("ON LOAD -- Last Week");
        $("#time_period").text("Time Period: Last Week");
        var citationsPath = "/citations";
        $.getJSON( citationsPath, {
          time_scope: "Last Week",
          format: "json"
        })
        .done(function( data ) {
          var cur_total = 0;
          $.each(data, function() {
            cur_total += this.value;
          }); 
          $("#total_citations").text("Total Citations: " + cur_total);
          heatmapChart(data);
        });
      })();

      datasetpicker.enter()
        .append("input")
        .attr("value", function(d){ 
          //console.log("datatsetpicker " + d);
          return d; })
        .attr("type", "button")
        .attr("class", "dataset-button")
        .on("click", function(d) {
          $("#time_period").text("Time Period: Loading...");
          $("#total_citations").text("Total Citations: Loading...");
          (function() {
            var citationsPath = "/citations";
            $.getJSON( citationsPath, {
              time_scope: d,
              format: "json"
            })
            .done(function( data ) {
              var cur_total = 0;
              $.each(data, function() {
                cur_total += this.value;
              }); 
              $("#total_citations").text("Total Citations: " + cur_total);
              $("#time_period").text("Time Period: " + d);
              heatmapChart(data);
            });
          })();
        });
  });

app/views/citations/new.html.haml
%h1 New citation

= render 'form'

= link_to 'Back', citations_path

app/views/citations/show.html.haml
%p#notice= notice

%p
  %b Citation num:
  = @citation.citation_num
%p
  %b Issue date:
  = @citation.issue_date
%p
  %b Street location:
  = @citation.street_location
%p
  %b Violation:
  = @citation.violation
%p
  %b Geometry:
  = @citation.geometry_id

= link_to 'Edit', edit_citation_path(@citation)
\|
= link_to 'Back', citations_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' unless current_page?(root_path) %>
    </header>
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Abq Parking Citations'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Abq Parking Citations'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#about">About</a>
                </li>
                <li>
                    <a href="#services">Services</a>
                </li>
                <li>
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Header -->
<a name="about"></a>
<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Landing Page</h1>
                    <h3>A Template by Start Bootstrap</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->

<a  name="services"></a>
<div class="content-section-a">

    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Death to the Stock Photo:<br>Special Thanks</h2>
                <p class="lead">A special thanks to <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a> for providing the photographs that you see in this template. Visit their website to become a member.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="http://ironsummitmedia.github.io/startbootstrap-landing-page/img/ipad.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-b">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">3D Device Mockups<br>by PSDCovers</h2>
                <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by <a target="_blank" href="http://www.psdcovers.com/">PSDCovers</a>! Visit their website to download some of their awesome, free photoshop actions!</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <img class="img-responsive" src="http://ironsummitmedia.github.io/startbootstrap-landing-page/img/dog.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
                <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="http://ironsummitmedia.github.io/startbootstrap-landing-page/img/phones.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<a  name="contact"></a>
<div class="banner">

    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <h2>Connect to Start Bootstrap:</h2>
            </div>
            <div class="col-lg-6">
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.banner -->

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
                <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
            </div>
        </div>
    </div>
</footer>